version: "3.8"

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-06-13T22-53-53Z
  command: server --console-address ":9090" mnt/data
  ports:
    - "9000:9000"
    - "9090:9090"
  # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  postgres:
    restart: always
    image: postgres:14.11
    container_name: psql_db
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DBNAME}
    ports:
      - 5001:5432
    volumes:
      - .postgres:/var/lib/postgres/data/pgdata

  minio1:
    <<: *minio-common
    hostname: minio1
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_VOLUMES: ${MINIO_VOLUMES}
    volumes:
      - type: bind
        source: /home/kicker/mad_soft_test/.minio
        target: /mnt/data
      - type: bind
        source: /home/kicker/mad_soft_test/minio
        target: /etc/config.env